version: 2.0.{build}
image: Ubuntu1804
install:
  - sudo apt update -qq
  - sudo apt install -yqq -o=Dpkg::Progress-Fancy=0 g++ make pkg-config
  - sudo apt install -yqq -o=Dpkg::Progress-Fancy=0 qt5-default qtdeclarative5-dev
  - sudo apt install -yqq -o=Dpkg::Progress-Fancy=0 libblkid-dev libfuse-dev
  - qmake -v
build_script:
  - cd build
  - qmake ../src/GostCrypt.pro
  - make -j $(cat /proc/cpuinfo | grep processor | wc -l)
test_script:
   - ./testCoreAsUser -r junit -o testResults/CoreAsUser.xml
   - sudo ./testCoreAsRoot -r junit -o testResults/CoreAsRoot.xml
   - sudo ./testFuseService -r junit -o testResults/FuseService.xml
   - sudo ./testVolume -r junit -o testResults/Volume.xml
artifacts:
  - path: build/GostCrypt
    name: GostCrypt executable
    type: file
on_finish:
  - find "$APPVEYOR_BUILD_FOLDER/build/testResults/" -type f -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID"
  
