version: 2.0.{build}
image: Ubuntu1804
install:
  - sudo apt-get update -qq
  - export DEBIAN_FRONTEND=noninteractive
  - sudo -E apt-get install -y g++ make pkg-config >> /dev/null
  - sudo -E apt-get install -y qt5-default qtdeclarative5-dev >> /dev/null
  - sudo -E apt-get install -y libblkid-dev libfuse-dev >> /dev/null
  - sudo -E apt-get install -y rpm >> /dev/null
  - rvm use 2.5.3 >> /dev/null
  - gem install --silent --no-ri --no-rdoc fpm
  - qmake -v
  - fpm -v
build_script:
  - cd build
  - qmake ../src/GostCrypt.pro
  - make -j $(cat /proc/cpuinfo | grep processor | wc -l)
test_script:
   - ./testCoreAsUser -r junit -o testResults/CoreAsUser.xml
   - sudo ./testCoreAsRoot -r junit -o testResults/CoreAsRoot.xml
   - sudo ./testFuseService -r junit -o testResults/FuseService.xml
   - sudo ./testVolume -r junit -o testResults/Volume.xml
artifacts:
  - path: build/GostCrypt
    name: GostCrypt executable
    type: file
on_finish:
  - find "$APPVEYOR_BUILD_FOLDER/build/testResults/" -type f -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID"
on_success:
  - mkdir pkgs
  # Create RPM package
  - ruby $(which fpm) -s dir -t rpm -n gostcrypt --rpm-digest sha256 --version $APPVEYOR_BUILD_VERSION --license GPLv3 -m hantoine02@gmail.com -d qt5 -d libblkid -d fuse -p pkgs GostCrypt=/usr/bin/gostcrypt
  - appveyor PushArtifact $(find ./pkgs -name "*.rpm") -Type File -DeploymentName "GostCrypt RPM package"
  
