version: 2.0.{build}
image: Ubuntu1804
install:
  - sudo apt-get update -qq
  - export DEBIAN_FRONTEND=noninteractive
  - sudo -E apt-get install -y g++ make pkg-config >> /dev/null
  - sudo -E apt-get install -y qt5-default qtdeclarative5-dev >> /dev/null
  - sudo -E apt-get install -y libblkid-dev libfuse-dev >> /dev/null
  - sudo -E apt-get install -y rpm >> /dev/null
  - rvm use 2.5.3 >> /dev/null
  - gem install --silent --no-ri --no-rdoc fpm
  - qmake -v
  - fpm -v
build_script:
  - cd build
  - qmake ../src/GostCrypt.pro
  - make -j $(cat /proc/cpuinfo | grep processor | wc -l)
test_script:
   - ./testCoreAsUser -r junit -o testResults/CoreAsUser.xml
   - sudo ./testCoreAsRoot -r junit -o testResults/CoreAsRoot.xml
   - sudo ./testFuseService -r junit -o testResults/FuseService.xml
   - sudo ./testVolume -r junit -o testResults/Volume.xml
cache:
   - build/debian-build-docker-saved
artifacts:
  - path: build/GostCrypt
    name: GostCrypt executable
    type: file
on_finish:
  - find "$APPVEYOR_BUILD_FOLDER/build/testResults/" -type f -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID"
on_success:
  # Create RPM package
  - ruby $(which fpm) -s dir -t rpm -n gostcrypt --rpm-digest sha256 --version $APPVEYOR_BUILD_VERSION --license GPLv3 -m hantoine02@gmail.com -d qt5 -d libblkid -d fuse GostCrypt=/usr/bin/gostcrypt
  - appveyor PushArtifact $(find . -name "*.rpm") -Type File -DeploymentName "GostCrypt RPM package"
  # Create deb package 
  - ruby $(which fpm) -s dir -t deb -n gostcrypt --version $APPVEYOR_BUILD_VERSION --license GPLv3 -m hantoine02@gmail.com -d qt5-default -d libqt5qml5 -d libqt5quick5 -d libblkid1 -d libfuse2 --deb-no-default-config-files GostCrypt=/usr/bin/gostcrypt
  - appveyor PushArtifact $(find . -name "*.deb") -Type File -DeploymentName "GostCrypt Ubuntu deb package"
  # Create deb package for debian
  - if [ -e "debian-build-docker-saved" ] ; then docker load -i debian-build-docker-saved ; fi
  - docker build debian-build-docker -t gostcrypt-debian-build --cache-from gostcrypt-debian-build
  - docker save -o debian-build-docker-saved gostcrypt-debian-build
  - docker run --privileged -e APPVEYOR_BUILD_VERSION=$APPVEYOR_BUILD_VERSION -v $(readlink -f ..):/gostcrypt gostcrypt-debian-build 
  - cd ..
  - DEBIAN_DEB_PACKAGE=$(find build-debian -name "*.deb")
  - appveyor PushArtifact $DEBIAN_DEB_PACKAGE -Type File -DeploymentName "GostCrypt Debian deb package" -FileName $DEBIAN_DEB_PACKAGE
